from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable
)


# ============================================================
# COLOUR PALETTE
# ============================================================

PRIMARY = colors.HexColor("#4A90E2")
SUCCESS = colors.HexColor("#2ECC71")
WARNING = colors.HexColor("#F1C40F")
DANGER = colors.HexColor("#E74C3C")

LIGHT_BLUE = colors.HexColor("#EAF3FF")
LIGHT_GREY = colors.HexColor("#F7F7F7")
TEXT = colors.HexColor("#2C3E50")
BORDER = colors.HexColor("#D8D8D8")


# ============================================================
# STYLES
# ============================================================

styles = getSampleStyleSheet()

styles.add(
    ParagraphStyle(
        name="ReportTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=24,
        alignment=TA_CENTER,
        textColor=PRIMARY,
        spaceAfter=6
    )
)

styles.add(
    ParagraphStyle(
        name="Subtitle",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=10,
        textColor=colors.grey,
        spaceAfter=15
    )
)

styles.add(
    ParagraphStyle(
        name="Section",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=15,
        textColor=PRIMARY,
        spaceBefore=12,
        spaceAfter=8
    )
)

styles.add(
    ParagraphStyle(
        name="Body",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10,
        leading=18,
        textColor=TEXT
    )
)

styles.add(
    ParagraphStyle(
        name="Small",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.grey
    )
)


# ============================================================
# FOOTER
# ============================================================

def draw_footer(canvas, doc):

    canvas.saveState()

    canvas.setFont("Helvetica", 9)

    canvas.setFillColor(colors.grey)

    canvas.drawString(
        doc.leftMargin,
        18,
        "Generated by Customer Churn Intelligence Dashboard"
    )

    canvas.drawRightString(
        A4[0] - doc.rightMargin,
        18,
        f"Page {doc.page}"
    )

    canvas.restoreState()


# ============================================================
# HORIZONTAL LINE
# ============================================================

def divider(elements):

    elements.append(
        HRFlowable(
            width="100%",
            thickness=1,
            color=PRIMARY
        )
    )

    elements.append(
        Spacer(1,10)
    )


# ============================================================
# SECTION TITLE
# ============================================================

def section_title(elements, title):

    elements.append(
        Spacer(1,12)
    )

    elements.append(
        Paragraph(
            title,
            styles["Section"]
        )
    )

    divider(elements)


# ============================================================
# STANDARD TABLE
# ============================================================

def create_table(data, widths=None):

    table = Table(
        data,
        colWidths=widths
    )

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),PRIMARY),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

            ("BACKGROUND",(0,1),(0,-1),LIGHT_GREY),

            ("GRID",(0,0),(-1,-1),0.5,BORDER),

            ("BOTTOMPADDING",(0,0),(-1,-1),8),

            ("TOPPADDING",(0,0),(-1,-1),8),

            ("FONTNAME",(0,1),(-1,-1),"Helvetica")

        ])

    )

    return table


# ============================================================
# BULLET SECTION
# ============================================================

def add_bullets(elements, items):

    if not items:

        elements.append(

            Paragraph(

                "No information available.",

                styles["Body"]

            )

        )

        return

    for item in items:

        elements.append(

            Paragraph(

                f"• {item}",

                styles["Body"]

            )

        )

    elements.append(
        Spacer(1,8)
    )


# ============================================================
# MAIN PDF FUNCTION
# ============================================================

def generate_pdf(report_data):

    buffer = BytesIO()

    doc = SimpleDocTemplate(

        buffer,

        pagesize=A4,

        leftMargin=40,

        rightMargin=40,

        topMargin=40,

        bottomMargin=50

    )

    elements = []

    # ========================================================
    # REPORT HEADER
    # ========================================================

    elements.append(

        Paragraph(

            "Customer Churn Analysis Report",

            styles["ReportTitle"]

        )

    )

    elements.append(

        Paragraph(

            "Customer Churn Intelligence Dashboard",

            styles["Subtitle"]

        )

    )

    elements.append(

        Paragraph(

            datetime.now().strftime(
                "%d %B %Y | %I:%M %p"
            ),

            styles["Subtitle"]

        )

    )

    elements.append(
        Spacer(1,15)
    )
        # ========================================================
    # EXECUTIVE SUMMARY
    # ========================================================

    section_title(elements, "📊 Executive Summary")

    prediction_text = (
        "Likely to Churn"
        if report_data["prediction"]
        else "Likely to Stay"
    )

    summary_table = [

        ["Metric", "Value"],

        ["Prediction", prediction_text],

        ["Risk Level", report_data["risk_level"]],

        [
            "Churn Probability",
            f"{report_data['churn_probability']:.2f}%"
        ],

        [
            "Stay Probability",
            f"{report_data['stay_probability']:.2f}%"
        ]

    ]

    elements.append(
        create_table(
            summary_table,
            widths=[220,220]
        )
    )

    elements.append(
        Spacer(1,18)
    )


    # ========================================================
    # MODEL CONFIDENCE
    # ========================================================

    section_title(elements, "🎯 Model Confidence")

    confidence = abs(
        report_data["churn_probability"] - 50
    ) * 2

    if confidence >= 80:

        confidence_level = "High"

        confidence_message = (
            "The model is highly confident because the "
            "customer profile strongly matches historical "
            "customer behaviour."
        )

    elif confidence >= 50:

        confidence_level = "Moderate"

        confidence_message = (
            "The prediction contains both churn and "
            "retention indicators."
        )

    else:

        confidence_level = "Low"

        confidence_message = (
            "This prediction lies close to the decision "
            "boundary and should be interpreted carefully."
        )


    confidence_table = [

        ["Metric", "Value"],

        [
            "Confidence Score",
            f"{confidence:.1f}%"
        ],

        [
            "Confidence Level",
            confidence_level
        ]

    ]

    elements.append(

        create_table(

            confidence_table,

            widths=[220,220]

        )

    )

    elements.append(
        Spacer(1,8)
    )

    elements.append(

        Paragraph(

            confidence_message,

            styles["Body"]

        )

    )

    elements.append(
        Spacer(1,18)
    )


    # ========================================================
    # CUSTOMER PROFILE
    # ========================================================

    section_title(elements, "👤 Customer Profile")


    # --------------------------------------------------------
    # Personal Information
    # --------------------------------------------------------

    elements.append(

        Paragraph(

            "<b>Personal Information</b>",

            styles["Body"]

        )

    )

    personal_table = [

        ["Attribute", "Value"],

        [
            "Gender",
            report_data["gender"]
        ],

        [
            "Senior Citizen",
            report_data["senior_citizen"]
        ],

        [
            "Partner",
            report_data["partner"]
        ],

        [
            "Dependents",
            report_data["dependents"]
        ]

    ]

    elements.append(

        create_table(

            personal_table,

            widths=[220,220]

        )

    )

    elements.append(
        Spacer(1,15)
    )


    # --------------------------------------------------------
    # Service Information
    # --------------------------------------------------------

    elements.append(

        Paragraph(

            "<b>Service Information</b>",

            styles["Body"]

        )

    )

    service_table = [

        ["Attribute", "Value"],

        [
            "Tenure",
            f"{report_data['tenure']} Months"
        ],

        [
            "Contract",
            report_data["contract"]
        ],

        [
            "Internet Service",
            report_data["internet_service"]
        ],

        [
            "Tech Support",
            report_data["tech_support"]
        ]

    ]

    elements.append(

        create_table(

            service_table,

            widths=[220,220]

        )

    )

    elements.append(
        Spacer(1,15)
    )


    # --------------------------------------------------------
    # Billing Information
    # --------------------------------------------------------

    elements.append(

        Paragraph(

            "<b>Billing Information</b>",

            styles["Body"]

        )

    )

    billing_table = [

        ["Attribute", "Value"],

        [
            "Monthly Charges",
            f"£{report_data['monthly_charges']:.2f}"
        ],

        [
            "Total Charges",
            f"£{report_data['total_charges']:.2f}"
        ]

    ]

    elements.append(

        create_table(

            billing_table,

            widths=[220,220]

        )

    )

    elements.append(
        Spacer(1,20)
    )
        # ========================================================
    # FEATURE IMPACT ANALYSIS
    # ========================================================

    section_title(elements, "📊 Feature Impact Analysis")

    feature_scores = report_data.get("feature_scores", {})

    if feature_scores:

        feature_table = [

            ["Feature", "Impact Score"]

        ]

        sorted_features = sorted(
            feature_scores.items(),
            key=lambda x: x[1],
            reverse=True
        )

        for feature, score in sorted_features:

            feature_table.append(

                [
                    feature,
                    str(score)
                ]

            )

        elements.append(

            create_table(

                feature_table,

                widths=[320,120]

            )

        )

        elements.append(
            Spacer(1,8)
        )

        elements.append(

            Paragraph(

                "Positive values indicate factors contributing "
                "towards churn, while negative values indicate "
                "customer retention characteristics.",

                styles["Small"]

            )

        )

    else:

        elements.append(

            Paragraph(

                "No feature impact information available.",

                styles["Body"]

            )

        )

    elements.append(
        Spacer(1,18)
    )


    # ========================================================
    # CHURN RISK FACTORS
    # ========================================================

    section_title(elements, "⚠️ Churn Risk Factors")

    risk_factors = report_data.get(
        "risk_factors",
        []
    )

    if risk_factors:

        add_bullets(
            elements,
            risk_factors
        )

    else:

        elements.append(

            Paragraph(

                "No significant churn risk factors detected.",

                styles["Body"]

            )

        )

    elements.append(
        Spacer(1,15)
    )


    # ========================================================
    # POSITIVE FACTORS
    # ========================================================

    section_title(elements, "✅ Positive Factors")

    positive_factors = report_data.get(
        "positive_factors",
        []
    )

    if positive_factors:

        add_bullets(
            elements,
            positive_factors
        )

    else:

        elements.append(

            Paragraph(

                "No strong customer retention factors identified.",

                styles["Body"]

            )

        )

    elements.append(
        Spacer(1,20)
    )
        # ========================================================
    # RECOMMENDED ACTIONS
    # ========================================================

    section_title(elements, "💡 Recommended Actions")

    recommendations = report_data.get("recommendations", [])

    if recommendations:

        add_bullets(
            elements,
            recommendations
        )

    else:

        elements.append(

            Paragraph(

                "No recommendations available.",

                styles["Body"]

            )

        )

    elements.append(
        Spacer(1,18)
    )


    # ========================================================
    # BUSINESS INSIGHT
    # ========================================================

    section_title(elements, "📈 Business Insight")

    insight = report_data.get(
        "business_insight",
        "No business insight available."
    )

    elements.append(

        Paragraph(

            insight.replace("\n", "<br/>"),

            styles["Body"]

        )

    )

    elements.append(
        Spacer(1,20)
    )


    # ========================================================
    # MODEL INFORMATION
    # ========================================================

    section_title(elements, "🤖 Model Information")

    model_table = [

        ["Property", "Value"],

        [
            "Machine Learning Model",
            "Logistic Regression"
        ],

        [
            "Dataset",
            "IBM Telco Customer Churn"
        ],

        [
            "Framework",
            "Scikit-Learn"
        ],

        [
            "Dashboard",
            "Streamlit"
        ]

    ]

    elements.append(

        create_table(

            model_table,

            widths=[220,220]

        )

    )

    elements.append(
        Spacer(1,20)
    )


    # ========================================================
    # DISCLAIMER
    # ========================================================

    section_title(elements, "📄 Disclaimer")

    disclaimer = """
This report has been generated automatically by the Customer Churn Intelligence Dashboard.

The prediction is based on a Logistic Regression model trained on the IBM Telco Customer Churn dataset.

The insights, recommendations and feature impacts are intended to assist business decision-making and should not be considered absolute predictions of future customer behaviour.
"""

    elements.append(

        Paragraph(

            disclaimer.replace("\n", "<br/>"),

            styles["Body"]

        )

    )

    elements.append(
        Spacer(1,20)
    )


    # ========================================================
    # BUILD PDF
    # ========================================================

    doc.build(

        elements,

        onFirstPage=draw_footer,

        onLaterPages=draw_footer

    )

    pdf = buffer.getvalue()

    buffer.close()

    return pdf